<a href="https://colab.research.google.com/github/rkuma9141/RaviRanjan-kumar/blob/main/Firstlecturenumy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##numpy as machine learning

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
! pip install numpy

In [ ]:
x=np.random.randint(10,size=(3,4,5))

In [ ]:
x


array([[[9, 8, 6, 8, 5],
        [3, 9, 5, 1, 9],
        [5, 5, 4, 6, 2],
        [2, 6, 7, 5, 4]],

       [[8, 9, 9, 3, 6],
        [0, 7, 4, 5, 0],
        [8, 2, 7, 4, 1],
        [6, 8, 1, 6, 4]],

       [[3, 5, 8, 8, 1],
        [1, 5, 7, 1, 7],
        [0, 5, 7, 2, 9],
        [6, 0, 3, 9, 5]]])

In [ ]:
#ndim
x.ndim

3

In [ ]:
x.size

60

In [ ]:
x.shape

(3, 4, 5)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.itemsize ## 8 bytes

8

In [ ]:
x.nbytes ## 8*60

480

## crteating array

In [ ]:
x=np.array(object=[1,2,3,4,5])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x=np.array(object=[1,2,3,4,5],dtype=complex)

In [ ]:
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
y=np.array((1,2,3,4,5,6,7))

In [ ]:
type(y)

numpy.ndarray

## create Array From Scratch

In [ ]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full(shape=(4,4),fill_value=3.1456)

array([[3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456]])

creating array from scratch continud

In [ ]:
np.arange(start=0,stop=20,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [ ]:
np.arange(1,100,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [ ]:
np.linspace(start=0,stop=1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,3,))

array([[0.48815708, 0.64211047, 0.96043428],
       [0.37873263, 0.89313723, 0.53540328],
       [0.54158779, 0.92538641, 0.7871858 ]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[-0.66112929,  0.59654383,  2.63689713],
       [ 1.40208516,  1.76801525,  0.51331632],
       [-0.99531273,  0.40045163,  1.39274021]])

In [ ]:
np.random.normal(2,4,(4,4))

array([[ 2.23751315,  9.10342491,  4.35424294,  0.64487291],
       [ 4.61713007,  2.01911265,  2.26846588, -3.98641808],
       [ 8.19399362,  1.87287129,  0.70701393,  0.39720504],
       [-0.31374875,  9.64480634,  6.67990165,  3.06058046]])

In [ ]:
np.random.normal(4,4,(5,5))

array([[ 6.20531449,  9.40601837,  1.239745  ,  0.78942784,  1.33006067],
       [-2.37008877,  1.35596105,  7.41917842,  5.46851464, -0.36446729],
       [ 6.61930463,  0.5810602 , -0.43434008,  9.88408148, -1.60059627],
       [-2.06605957, -3.26894344,  9.26999808,  4.20393862,  3.62965459],
       [-5.7818294 ,  2.23560458, -2.00504659,  6.54128236,  3.63304951]])

In [ ]:
np.random.randint(10,100,size=(2,3))

array([[78, 89, 35],
       [54, 63, 95]])

In [ ]:
np.random.randint(20,200,size=(3,3))

array([[ 41,  37,  98],
       [187,  20,  78],
       [174, 180, 172]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty(4)

array([1., 1., 1., 1.])

In [ ]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.empty(6)

array([4.01539484e-315, 0.00000000e+000, 2.14321575e-312, 3.64522198e-306,
       8.38543018e+266, 4.10074486e-322])

## Array index and slicing

In [ ]:
#Bool
# int
#complex
# float
#object

In [ ]:
x=np.random.randint(10,100,(4,3))

In [ ]:
x

array([[52, 92, 67],
       [42, 49, 63],
       [79, 78, 29],
       [46, 89, 25]])

In [ ]:
x[1,2]

np.int64(63)

In [ ]:
x[2,2]

np.int64(29)

In [ ]:
x[1,0]

np.int64(42)

In [ ]:
x[2]

array([79, 78, 29])

In [ ]:
x[-1]

array([46, 89, 25])

In [ ]:
x[-2,-1]

np.int64(29)

In [ ]:
##x[start:end:stepsize,start:end:stepsize]

In [ ]:
x[1:4]

array([[42, 49, 63],
       [79, 78, 29],
       [46, 89, 25]])

In [ ]:
x[1:3]

array([[42, 49, 63],
       [79, 78, 29]])

In [ ]:
x[1:3,1:3]

array([[49, 63],
       [78, 29]])

In [ ]:
np.random.seed(6)
y=np.random.randint(0,100,(7,7))

In [ ]:
y

array([[10, 73, 99, 84, 79, 80, 62],
       [25,  1, 75, 77, 57, 26, 33],
       [68, 33,  8,  2, 76, 84, 91],
       [31, 66,  5, 26, 15, 89, 86],
       [43, 69, 49,  4, 62, 80, 66],
       [66, 63, 19, 85, 28, 43, 57],
       [ 5, 50, 26, 78, 40, 69, 70]])

In [ ]:
y[2:6,2]

array([ 8,  5, 49, 19])

In [ ]:
y[3:6,3]

array([26,  4, 85])

In [ ]:
y[1:7:2,1:7:2]

array([[ 1, 77, 26],
       [66, 26, 89],
       [63, 85, 43]])

##Array slicing as views

In [ ]:
y

array([[10, 73, 99, 84, 79, 80, 62],
       [25,  1, 75, 77, 57, 26, 33],
       [68, 33,  8,  2, 76, 84, 91],
       [31, 66,  5, 26, 15, 89, 86],
       [43, 69, 49,  4, 62, 80, 66],
       [66, 63, 19, 85, 28, 43, 57],
       [ 5, 50, 26, 78, 40, 69, 70]])

In [ ]:
a=y[1:7:2,1:7:2]

In [ ]:
a

array([[ 1, 77, 26],
       [66, 26, 89],
       [63, 85, 43]])

In [ ]:
c=y[1:7:2,1:7:2]

In [ ]:
c

array([[ 1, 77, 26],
       [66, 26, 89],
       [63, 85, 43]])

In [ ]:
#insert lvalue
a[0,0]=999

In [ ]:
a

array([[999,  77,  26],
       [ 66,  26,  89],
       [ 63,  85,  43]])

In [ ]:
a[2,2]=999

In [ ]:
a

array([[999,  77,  26],
       [ 66,  26,  89],
       [ 63,  85, 999]])

In [ ]:
y

array([[ 10,  73,  99,  84,  79,  80,  62],
       [ 25, 999,  75,  77,  57,  26,  33],
       [ 68,  33,   8,   2,  76,  84,  91],
       [ 31,  66,   5,  26,  15,  89,  86],
       [ 43,  69,  49,   4,  62,  80,  66],
       [ 66,  63,  19,  85,  28, 999,  57],
       [  5,  50,  26,  78,  40,  69,  70]])

In [ ]:
a=y[1:7:2,1:7:2]

In [ ]:
a

array([[999,  77,  26],
       [ 66,  26,  89],
       [ 63,  85, 999]])

In [ ]:
a[0,0]=100

In [ ]:
a

array([[100,  77,  26],
       [ 66,  26,  89],
       [ 63,  85, 999]])

In [ ]:
a[2,2]=100

In [ ]:
a

array([[100,  77,  26],
       [ 66,  26,  89],
       [ 63,  85, 100]])

In [ ]:
y

array([[ 10,  73,  99,  84,  79,  80,  62],
       [ 25, 100,  75,  77,  57,  26,  33],
       [ 68,  33,   8,   2,  76,  84,  91],
       [ 31,  66,   5,  26,  15,  89,  86],
       [ 43,  69,  49,   4,  62,  80,  66],
       [ 66,  63,  19,  85,  28, 100,  57],
       [  5,  50,  26,  78,  40,  69,  70]])

In [ ]:
y.shape

(7, 7)

In [ ]:
np.random.seed(6)
z=np.random.randint(0,100,(5,3))


In [ ]:
z

array([[10, 73, 99],
       [84, 79, 80],
       [62, 25,  1],
       [75, 77, 57],
       [26, 33, 68]])

In [ ]:
z.reshape(3,5)

array([[10, 73, 99, 84, 79],
       [80, 62, 25,  1, 75],
       [77, 57, 26, 33, 68]])

In [ ]:
## concatenate
np.random.seed(0)
a=np.random.randint(0,100,(2,3))
b=np.random.randint(10,500,(2,3))

In [ ]:
a

array([[44, 47, 64],
       [67, 67,  9]])

In [ ]:
b

array([[221, 287, 252],
       [302,  97,  80]])

In [ ]:
np.concatenate([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [221, 287, 252],
       [302,  97,  80]])

In [ ]:
np.concatenate([a,b],axis=1)

array([[ 44,  47,  64, 221, 287, 252],
       [ 67,  67,   9, 302,  97,  80]])

In [ ]:
np.vstack([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [221, 287, 252],
       [302,  97,  80]])

In [ ]:
np.hstack([a,b])

array([[ 44,  47,  64, 221, 287, 252],
       [ 67,  67,   9, 302,  97,  80]])

## mathematical operations on numpy arrays

In [ ]:
x=np.arange(4)

In [ ]:
x

array([0, 1, 2, 3])

In [ ]:
x+5

array([5, 6, 7, 8])

In [ ]:
x-2

array([-2, -1,  0,  1])

In [ ]:
x/2

array([0. , 0.5, 1. , 1.5])

In [ ]:
x*2

array([0, 2, 4, 6])

In [ ]:
x//2

array([0, 0, 1, 1])

In [ ]:
x%2

array([0, 1, 0, 1])

In [ ]:
x**2

array([0, 1, 4, 9])

In [ ]:
np.add(x,2)

array([2, 3, 4, 5])

In [ ]:
np.subtract(x,2)

array([-2, -1,  0,  1])

## boolean indexing

In [ ]:
z

array([[10, 73, 99],
       [84, 79, 80],
       [62, 25,  1],
       [75, 77, 57],
       [26, 33, 68]])

In [ ]:
z>50

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [ ]:
z[z>50]

array([73, 99, 84, 79, 80, 62, 75, 77, 57, 68])

In [ ]:
np.exp(z)

array([[2.20264658e+04, 5.05239363e+31, 9.88903032e+42],
       [3.02507732e+36, 2.03828107e+34, 5.54062238e+34],
       [8.43835667e+26, 7.20048993e+10, 2.71828183e+00],
       [3.73324200e+32, 2.75851345e+33, 5.68572000e+24],
       [1.95729609e+11, 2.14643580e+14, 3.40427605e+29]])

In [ ]:
np.exp2(z)

array([[1.02400000e+03, 9.44473297e+21, 6.33825300e+29],
       [1.93428131e+25, 6.04462910e+23, 1.20892582e+24],
       [4.61168602e+18, 3.35544320e+07, 2.00000000e+00],
       [3.77789319e+22, 1.51115727e+23, 1.44115188e+17],
       [6.71088640e+07, 8.58993459e+09, 2.95147905e+20]])

In [ ]:
np.log(x)

array([      -inf, 0.        , 0.69314718, 1.09861229])

In [ ]:
np.sum(z)

np.int64(849)

In [ ]:
np.var(z)

np.float64(835.7066666666666)

In [ ]:
np.std(z)

np.float64(28.9085915718263)

In [ ]:
np.min(z)

np.int64(1)

In [ ]:
np.max(z)

np.int64(99)

In [ ]:
np.median(z)

np.float64(68.0)

In [ ]:
np.argmin(z)

np.int64(8)

In [ ]:
np.argmax(z)

np.int64(2)

In [ ]:
np.sum(z)

np.int64(849)

In [ ]:
np.cumsum(z)

array([ 10,  83, 182, 266, 345, 425, 487, 512, 513, 588, 665, 722, 748,
       781, 849])

In [ ]:
np.exp(z)

array([[2.20264658e+04, 5.05239363e+31, 9.88903032e+42],
       [3.02507732e+36, 2.03828107e+34, 5.54062238e+34],
       [8.43835667e+26, 7.20048993e+10, 2.71828183e+00],
       [3.73324200e+32, 2.75851345e+33, 5.68572000e+24],
       [1.95729609e+11, 2.14643580e+14, 3.40427605e+29]])

In [ ]:
np.log(z)

array([[2.30258509, 4.29045944, 4.59511985],
       [4.4308168 , 4.36944785, 4.38202663],
       [4.12713439, 3.21887582, 0.        ],
       [4.31748811, 4.34380542, 4.04305127],
       [3.25809654, 3.49650756, 4.21950771]])

In [ ]:
np.var(z)

np.float64(835.7066666666666)

In [ ]:
np.where(z)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [ ]:
## set operation

In [ ]:
np.unique(z)

array([ 1, 10, 25, 26, 33, 57, 62, 68, 73, 75, 77, 79, 80, 84, 99])